# Generated by Django 4.1 on 2022-09-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCargo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeMedicion', models.DateTimeField()),
                ('oximetria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuenciaRespiratoria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuenciaCardiaca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presionArterial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glicemias', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoidentificacion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroIdentificacion', models.CharField(max_length=45)),
                ('nombrePP', models.CharField(max_length=45)),
                ('apellidoPP', models.CharField(max_length=45)),
                ('direccionPP', models.CharField(max_length=45)),
                ('municipioPP', models.CharField(max_length=45)),
                ('departamentoPP', models.CharField(max_length=45)),
                ('cargo_idCargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalApp.cargo')),
                ('tipoIdentificacionPP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitalApp.tipoidentificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroIdentificacionPaciente', models.IntegerField()),
                ('nombrePaciente', models.CharField(max_length=45)),
                ('apellidosPaciente', models.CharField(max_length=45)),
                ('telefonoPaciente', models.IntegerField()),
                ('direccionPaciente', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('departamento', models.CharField(max_length=45)),
                ('fechaNacimientoPaciente', models.DateField()),
                ('generoPaciente', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45, unique=True)),
                ('tipoIdentificacionPP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitalApp.tipoidentificacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fehcaHistoriaClinica', models.DateField()),
                ('conceptoMedido', models.TextField(max_length=300)),
                ('sugerenciaMedica', models.TextField(max_length=300)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalApp.pacientes')),
                ('signosVitales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitalApp.signosvitales')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFamiliar', models.CharField(max_length=45)),
                ('apellidoFamilair', models.CharField(max_length=45)),
                ('telefonoFamilair', models.IntegerField()),
                ('direccionFamilair', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('departamento', models.CharField(max_length=45)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.familiar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.pacientes')),
                ('plantaPersonal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitalApp.plantapersonal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
