# Generated by Django 4.1 on 2022-09-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
