# Generated by Django 4.1 on 2022-09-10 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_usuariomodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientemodels',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
